services:
  back-end:
    build:
      context: back-end
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:postgresql://postgres-container/textEditorDb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres-container
  front-end:
    build:
      context: front-end
      dockerfile: Dockerfile
    ports:
      - 80:3000
    depends_on:
      - back-end
  postgres-container:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgres
    environment:
      POSTGRES_DB: textEditorDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  dbdata: